"""
This is the list of constants for my Mancala game.
"""

VERTICAL_OFFSET_OF_BOARD = 4
VERTICAL_OFFSET_OF_ERROR = 13
VERTICAL_OFFSET_OF_PROMPT = 12
MESSAGE_WAIT = 1.5
PIT_WIDTH = 3
PLAYER_PIT_COUNT = 6
STORE_WIDTH = 5
