"""
This is the list of constants for my Mancala game.
"""

HEIGHT_IDENTIFIERS = 1
HEIGHT_PIT = 3
HORIZONTAL_LINE = "-"
HORIZONTAL_OFFSET = 0
MESSAGE_WAIT = 1.5
OFFSET_HEIGHT_PIT = 2
OFFSET_WIDTH_PIT = 4
VERTICAL_LINE = "|"
VERTICAL_OFFSET_OF_BOARD = 4
VERTICAL_OFFSET_OF_ERROR = 13
VERTICAL_OFFSET_OF_HEADER = 0
VERTICAL_OFFSET_OF_PROMPT = 12
WIDTH_PIT = 5
WIDTH_STORE = 7
P1 = 0
P2 = 1
PLAYER_PIT_COUNT = 6
