import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";

import { Inter } from "next/font/google";

import { createTheme, MantineProvider } from "@mantine/core";

import { ConvexClientProvider } from "./ConvexClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
